version: '3.9'
name: rocket-gram
services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine3.19
    restart: always
    env_file:
      - postgres.env
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - '8888:8080'
    depends_on:
      - postgres

volumes:
  postgres_data: